# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e398292c826d7e128819c99dd0cbe7c9411803fe3160f72d350964c6fcc1f47a804939a1e4f9f8e66af13daa8ccd03207b6cc66887bfb8b1326646d323699446

test:
  secret_key_base: fe899081c6992104fbf21dbc923a500481d697fb33bbdfd7bb18bb82cf3c0b60f124e66c826a41eee8adba8b1e1e784687f176adb926284c04e57c3e497349c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
